services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: DOGATHER
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.mysql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3306:3306'
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -u root -proot']
      interval: 30s
      timeout: 10s
      retries: 3

  adminer:
    image: adminer
    container_name: adminer-container
    restart: always
    ports:
      - '8080:8080'

  nodeapp:
    container_name: nodeappcontainer
    build: .
    image: nodeapp:v1
    ports:
      - 8800:8800
    expose:
      - 8800
    environment:
      CLIENT_URL: 'http://localhost:5000'
      JWT_SECRET_KEY: 'secret'
      PORT: '8800'
      MYSQL_HOST: 'mysql'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_DATABASE: 'DOGATHER'
    depends_on:
      - mysql

volumes:
  mysql-data:
# /*
#  Run docker-compose up
# http://localhost:8080 adminer : user:root password:root database:DOGATHER
# */
